require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable

Gemspec/OrderedDependencies:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/SpaceAfterMethodName:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/ToJSON:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 32

Metrics/BlockLength:
  Max: 195

Metrics/ClassLength:
  Max: 170

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/MethodLength:
  Max: 23

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GlobalStdStream:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/LineLength:
  Max: 156

RSpec/AnyInstance:
  Enabled: false

RSpec/BeEq:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/ExampleLength:
  Max: 34

RSpec/ExampleWording:
  Enabled: false

RSpec/ExpectChange:
  Enabled: false

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MatchArray:
  Enabled: false

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleExpectations:
  Max: 16

RSpec/MultipleMemoizedHelpers:
  Max: 6

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/NotToNot:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/ReceiveCounts:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
