language: ruby
script: "bundle exec rspec"
rvm:
  - 2.2.2
  - 2.3.4
  - 2.4.1
  - 2.5
  - 2.6
  - 2.7
services:
  - redis-server
email:
  recipients:
    - piotrek@okonski.org
  on_success: change
  on_failure: always
